export type HangManWord = {
  word: string;
  hint: string;
};

export const wordList: HangManWord[] = [
  { word: 'ALGORITMO', hint: 'Secuencia de pasos lógicos para resolver un problema' },
  { word: 'VARIABLE', hint: 'Espacio en memoria para almacenar un dato que puede cambiar' },
  { word: 'FUNCION', hint: 'Bloque de código reutilizable que realiza una tarea específica' },
  { word: 'COMPILADOR', hint: 'Programa que traduce código fuente a lenguaje máquina' },
  { word: 'NAVEGADOR', hint: 'Software utilizado para acceder a sitios web' },
  { word: 'SERVIDOR', hint: 'Computadora que provee datos o servicios a otras computadoras' },
  { word: 'TECLADO', hint: 'Periférico de entrada principal para escribir en una PC' },
  { word: 'PANTALLA', hint: 'Dispositivo principal de salida visual' },
  { word: 'MEMORIA', hint: 'Donde se almacenan temporalmente los datos en ejecución' },
  { word: 'OBJETO', hint: 'Instancia de una clase en programación orientada a objetos' },
  { word: 'CLASE', hint: 'Plantilla o molde para crear objetos en programación' },
  { word: 'BUCLE', hint: 'Estructura de control que repite un bloque de código' },
  { word: 'ARREGLO', hint: 'Colección ordenada de elementos, también conocida como array' },
  { word: 'CADENA', hint: 'Secuencia de caracteres, como una palabra o texto (String)' },
  { word: 'ENTERO', hint: 'Tipo de dato numérico sin decimales' },
  { word: 'BOOLEANO', hint: 'Tipo de dato que solo admite dos valores' },
  { word: 'FRONTEND', hint: 'La parte visual y de interacción de una aplicación' },
  { word: 'BACKEND', hint: 'La lógica oculta del servidor y base de datos' },
  { word: 'ARCHIVO', hint: 'Conjunto de información almacenada en un dispositivo' },
  { word: 'CARPETA', hint: 'Directorio lógico donde se organizan los archivos' },
  { word: 'TERMINAL', hint: 'Interfaz de línea de comandos para dar órdenes al sistema' },
  { word: 'INTERFAZ', hint: 'Medio por el cual el usuario interactúa con la máquina' },
  { word: 'CONSTRUCTOR', hint: 'Método especial que se ejecuta al instanciar un objeto' },
  { word: 'PARAMETRO', hint: 'Valor que recibe una función para poder trabajar' },
  { word: 'PROMESA', hint: 'Objeto que representa el resultado de una operación asíncrona' },
  { word: 'SINTAXIS', hint: 'Conjunto de reglas para escribir código correctamente sin errores' },
  { word: 'LENGUAJE', hint: 'Sistema estructurado de comunicación para programar' },
  {
    word: 'LIBRERIA',
    hint: 'Conjunto de código preescrito por otros para facilitar el desarrollo',
  },
  {
    word: 'CONDICIONAL',
    hint: 'Estructura que ejecuta código solo si se cumple una regla (ej: If)',
  },
  { word: 'CONSTANTE', hint: 'Valor guardado en memoria que no puede ser modificado' },
  {
    word: 'REPOSITORIO',
    hint: 'Lugar donde se almacenan y gestionan las versiones de un proyecto',
  },
  { word: 'PAQUETE', hint: 'Conjunto de módulos y archivos distribuidos de forma empaquetada' },
  { word: 'PROTOCOLO', hint: 'Conjunto de reglas para la comunicación en red (ej: HTTP)' },
  { word: 'DISCO', hint: 'Dispositivo físico o sólido de almacenamiento persistente' },
  { word: 'PROCESADOR', hint: 'El cerebro de la computadora que ejecuta las instrucciones' },
  { word: 'HERENCIA', hint: 'Mecanismo para que una clase base transfiera sus atributos a otra' },
  { word: 'POLIMORFISMO', hint: 'Capacidad de un método u objeto de tomar múltiples formas' },
  {
    word: 'ENCAPSULAMIENTO',
    hint: 'Ocultamiento de los detalles internos y privados de una clase',
  },
  { word: 'ITERADOR', hint: 'Objeto que permite recorrer una colección de datos paso a paso' },
  { word: 'PUNTERO', hint: 'Variable que almacena la dirección de memoria de otro dato' },
  { word: 'BINARIO', hint: 'Sistema numérico de ceros y unos usado por las computadoras' },
  { word: 'CODIGO', hint: 'Conjunto de instrucciones legibles escritas por un programador' },
  { word: 'FRAMEWORK', hint: 'Entorno de trabajo que ofrece una estructura base, como Angular' },
  { word: 'METODO', hint: 'Nombre que recibe una función cuando pertenece a una clase' },
  { word: 'COMPONENTE', hint: 'Pieza de código independiente y reutilizable de una interfaz' },
  { word: 'RED', hint: 'Conjunto de computadoras conectadas entre sí' },
  { word: 'NUBE', hint: 'Servidores accesibles a través de internet para guardar datos' },
  { word: 'KERNEL', hint: 'El núcleo de un sistema operativo' },
  { word: 'EVENTO', hint: 'Acción que ocurre en el sistema, como hacer clic en un botón' },
  {
    word: 'DIRECTIVA',
    hint: 'Instrucción especial en el HTML para cambiar el DOM (muy de Angular)',
  },
  {
    word: 'ASINCRONISMO',
    hint: 'Concepto de ejecutar tareas en segundo plano sin frenar el sistema',
  },
  { word: 'MODULO', hint: 'Bloque de código agrupado que exporta funcionalidades específicas' },
];
